### ISSUE TITLE
我想知道这个API抗压能力怎么样

### ISSUE THREAD

**Issue by PureDark** [xCss/bing#10]
因为如果我放到我应用里用作顶部图片的获取接口、每天可能会有几千人调用几万次……
当然，我指的是 http://bing.ioliu.cn 这个
其实我一直在找公开的能获取到bing 随机图片的接口、找到几个都是私人搭建的感觉经不起我折腾2333

这个接口目前看来还能用，但是似乎是把图片下到服务器上进行处理的，感觉这太消耗你的服务器的性能了吧、如果能有直接redirect到bing的服务器原图地址的接口 对于压力就能放心多了……

**Comment by xCss** [comment]
额，目前的话。。。暂时还没有遇到量比较大的请求，但以实际带宽来看，应该没什么问题吧。。。

对了，你可以直接用 https://bing.ioliu.cn/v1/rand?type=json 这个接口来获取json数据，比直接用接口 https://bing.ioliu.cn/v1/rand 应该要来的更快一些
