### ISSUE TITLE
How many people use bing interface, please leave a message tell me

### ISSUE THREAD

**Issue by xCss** [xCss/bing#11]
Please leave the URL or the Github project links

方便的话，请留下网址或者Github项目地址。

**Comment by Jingle-seven** [comment]
+1

**Comment by Jingle-seven** [comment]
话说,模糊半径最大只能到50真的好吗,不怎么好看

**Comment by xCss** [comment]
@Jingle-seven 因为用的是七牛的接口，限制为：1~50，所以最大半径50已经是极限值了

**Comment by garyian168** [comment]
{ Error: ER_NO_SUCH_TABLE: Table 'bing.bing' doesn't exist，在你的项目也找不到sql文件

**Comment by xCss** [comment]
@garyian168 我只是提供接口和源码，数据库与数据之类的东西当然需要自己创建了啊

**Comment by garyian168** [comment]
数据结构应该也要给出来吧

**Comment by xCss** [comment]
@garyian168  数据结构：https://github.com/xCss/bing/tree/v2.1/db
