### ISSUE TITLE
无法调用第九张图片

### ISSUE THREAD

**Issue by Meekdai** [xCss/bing#13]
貌似是Bing官方只支持前8张图片
https://bing.ioliu.cn/v1/?d=9&w=1920&h=1200

**Comment by xCss** [comment]
@Meekdai 很抱歉，由于必应官方的接口提供的图片分辨率是不具有确定性的，有可能是不存在1920x1200分辨率的图片，你可以试试1920x1080:
https://bing.ioliu.cn/v1/?d=9&w=1920&h=1080  
![](https://bing.ioliu.cn/v1/?d=9&w=1920&h=1080)

**Comment by Meekdai** [comment]
原来如此，你的必应壁纸做的真棒！

**Comment by xCss** [comment]
😄O(∩_∩)O，感谢肯定。
