### ISSUE TITLE
新手求教

### ISSUE THREAD

**Issue by liuyasss** [xCss/bing#14]
能否一次返回多张图片？
我这么写对不对？---->https://bing.ioliu.cn/v1/?size=2 或者是https://bing.ioliu.cn/v1/?Size=2

不知道怎么写访问格式，这应该是个很简单的问题，浪费您时间了

**Comment by xCss** [comment]
@liuyasss 多张图片信息返回需要带`p(页码)`参数的，格式如下：
https://bing.ioliu.cn/v1/?p=1&size=2

**Comment by liuyasss** [comment]
@xCss 十分感谢
