### ISSUE TITLE
新手，不是很懂api里面的参数具体怎么用

### ISSUE THREAD

**Issue by PopeJoey** [xCss/bing#18]
比如我想获得第二页的图片，https://bing.ioliu.cn/v1{p=2}没用，https://bing.ioliu.cn/v1?p=2也不对。还有图片的长度和宽度的具体单位是什么？是和resolution里面的一样吗像1920*1200？

**Comment by wumusenlin** [comment]
> 比如我想获得第二页的图片，[https://bing.ioliu.cn/v1{p=2}没用，https://bing.ioliu.cn/v1?p=2也不对。还有图片的长度和宽度的具体单位是什么？是和resolution里面的一样吗像1920*1200？](https://bing.ioliu.cn/v1%7Bp=2%7D%E6%B2%A1%E7%94%A8%EF%BC%8Chttps://bing.ioliu.cn/v1?p=2%E4%B9%9F%E4%B8%8D%E5%AF%B9%E3%80%82%E8%BF%98%E6%9C%89%E5%9B%BE%E7%89%87%E7%9A%84%E9%95%BF%E5%BA%A6%E5%92%8C%E5%AE%BD%E5%BA%A6%E7%9A%84%E5%85%B7%E4%BD%93%E5%8D%95%E4%BD%8D%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%9F%E6%98%AF%E5%92%8Cresolution%E9%87%8C%E9%9D%A2%E7%9A%84%E4%B8%80%E6%A0%B7%E5%90%97%E5%83%8F1920*1200%EF%BC%9F)

https://bing.ioliu.cn/v1?w=1920&h=1080

**Comment by xCss** [comment]
#16
