### ISSUE TITLE
对 bing.ioliu.cn 的建议

### ISSUE THREAD

**Issue by h2y** [xCss/bing#20]
首先感谢提供这么漂亮一个壁纸网站！

我在使用过程中，不止一次卡在 <https://bing.ioliu.cn/photo/Econlockhatchee_EN-AU9702194142?force=download> 这样的下载链接中，大多数时候能够开始下载，少数时候会被卡住。

希望下载按钮直接指向 Bing 原图的下载地址。

**Comment by xCss** [comment]
@h2y bing官方会定期清理早些时候的图片(大概只保留最近半个月)，所以直接执行bing原图有可能会出现图片打不开的情况。

**Comment by h2y** [comment]
原来是这样，
那建议改进一下下载链接的相关代码，因为下载卡住的发生频率也不低 😞
