### ISSUE TITLE
pug文件咋用咩

### ISSUE THREAD

**Issue by insoxin** [xCss/bing#21]
百度了一大圈，各位函数介绍，却没最基础的🌚
现在有win和linux

**Comment by xCss** [comment]
https://pugjs.org/api/getting-started.html
https://segmentfault.com/a/1190000006198621
http://jade-lang.com/reference
https://github.com/pugjs/pug

**Comment by insoxin** [comment]
安装好node.js和npm。接下来🌚

**Comment by insoxin** [comment]
百度到了，需要编译
