### ISSUE TITLE
编译时提示错误

### ISSUE THREAD

**Issue by insoxin** [xCss/bing#22]
<img src="https://i.loli.net/2017/07/27/5979e2f4ec96b.png" alt="Screenshot_2017-07-27-20-54-21-0533808126.png" title="Screenshot_2017-07-27-20-54-21-0533808126.png" />

**Comment by xCss** [comment]
你可以先了解下[Express](http://www.expressjs.com.cn/)。
注意里面的[模板引擎](http://www.expressjs.com.cn/guide/using-template-engines.html)
