### ISSUE TITLE
希望加入渐进式图片格式

### ISSUE THREAD

**Issue by zhangyu921** [xCss/bing#27]
如题

**Comment by zhangyu921** [comment]
就。。。关上了。。。

**Comment by xCss** [comment]
@zhangyu921 抱歉，不是太懂你的意思。
请问什么是`渐进式图片格式`？是否是张鑫旭大神所说？http://www.zhangxinxu.com/wordpress/2013/01/progressive-jpeg-image-and-so-on/
如果是的话，创建`渐进式图片格式`需要手动用ps生成或者用C#程序转换。
如果不是这个，请说明。

**Comment by zhangyu921** [comment]
@xCss 是的说的就是这个~ 
你这边是没有储存图片是么？
没有的话那应该就没法做了

**Comment by xCss** [comment]
@zhangyu921 没有哦，存到七牛的~

**Comment by zhangyu921** [comment]
@xCss  看看这个能不能实现？ https://developer.qiniu.com/dora/manual/1270/the-advanced-treatment-of-images-imagemogr2
![image](https://user-images.githubusercontent.com/19166761/32038137-3050e346-b9ee-11e7-86ee-ca843f21ccaf.png)

**Comment by xCss** [comment]
@zhangyu921 大哥。。。虽然这个接口是免费的。。。
但是处理的流量不要钱吗？现在日均流量7G。。。都是我自己掏的。。。

**Comment by zhangyu921** [comment]
晓得了，辛苦了兄弟~ 👍
