### ISSUE TITLE
使用了随机图片后发现一个页面中加载的都是同一张图片？

### ISSUE THREAD

**Issue by QingShui23** [xCss/bing#28]
页面中加载的都是同一张图片？
可不可以做成每个链接的每次请求都是不同的图片嗯？

**Comment by QingShui23** [comment]
我的网站链接www.4zen.top

**Comment by xCss** [comment]
抱歉，我这边请求`rand接口`每次刷新都是随机的。
你的网站打不开，不太清楚你怎么调用的：
```
403 Forbidden
You don't have permission to access the URL on this server.
Powered by Tengine
```
![qq 20171028114950](https://user-images.githubusercontent.com/10877162/32130996-23064ef8-bbd6-11e7-8b1c-55cb012ceb79.png)

**Comment by QingShui23** [comment]
![mark](http://cdn.4zen.top/imgs/171028/FmdGdAGI4k.png) 会出现这种情况，同一个页面多次调用，随机出来的图片是同一张图片。

**Comment by QingShui23** [comment]
http://cdn.4zen.top/imgs/171028/FmdGdAGI4k.png
