### ISSUE TITLE
今天发现bing界面 国内版 和国际版 背景图不一致。。。

### ISSUE THREAD

**Issue by Chen-Hu** [xCss/bing#29]
今天背景图是小松鼠，我切到国际版发现壁纸变了。。。
我根据另外一个 bing壁纸的[开源项目](https://github.com/JavaProgrammerLB/BingWallpaper)把地址搞出来了。
以下地址返回 json结果。
//国内版
http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
//国际版
https://cn.bing.com/HPImageArchive.aspx?ensearch=1&idx=0&n=1&mkt=en-US&format=js

**Comment by xCss** [comment]
抱歉，我看到是一样的~
![tim 20171221164516](https://user-images.githubusercontent.com/10877162/34247691-6006b9d8-e66e-11e7-9619-3b8f441c7bc2.jpg)
![tim 20171221164527](https://user-images.githubusercontent.com/10877162/34247692-607b900a-e66e-11e7-8464-2fc3283eba92.jpg)

**Comment by Chen-Hu** [comment]
似乎和时间点有关系：
北京时间上午 08:46
https://cn.bing.com
国内版
![default](https://user-images.githubusercontent.com/6964498/34280823-7e9e2728-e6f5-11e7-93c9-e4fa230e6770.jpg)

国际版
![default](https://user-images.githubusercontent.com/6964498/34280839-91c5034e-e6f5-11e7-8703-0863aae674a3.jpg)

通过
https://cn.bing.com/HPImageArchive.aspx?ensearch=1&idx=0&n=1&mkt=en-US&format=js
返回的json
`{"images":[{"startdate":"20171221","fullstartdate":"201712210800","enddate":"20171222","url":"/az/hprichbg/rb/SolsticeSquirrel_EN-US6551849968_1920x1080.jpg","urlbase":"/az/hprichbg/rb/SolsticeSquirrel_EN-US6551849968","copyright":"Eastern gray squirrel peeking out of its den (© Darlyne A. Murawski/Getty Images)","copyrightlink":"http://www.bing.com/search?q=eastern+gray+squirrel&form=hpcapt&filters=HpDate:%2220171221_0800%22","quiz":"/search?q=Bing+homepage+quiz&filters=WQOskey:%22HPQuiz_20171221_SolsticeSquirrel%22&FORM=HPQUIZ","wp":false,"hsh":"e5c88fe140802d3b403f44cf032956b9","drk":1,"top":1,"bot":1,"hs":[]}],"tooltips":{"loading":"Loading...","previous":"Previous image","next":"Next image","walle":"This image is not available to download as wallpaper.","walls":"Download this image. Use of this image is restricted to wallpaper only."}}`

http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
返回的json
`{"images":[{"startdate":"20171221","fullstartdate":"201712211600","enddate":"20171222","url":"/az/hprichbg/rb/Wintersolstice1222_ZH-CN10807868228_1920x1080.jpg","urlbase":"/az/hprichbg/rb/Wintersolstice1222_ZH-CN10807868228","copyright":"【今日冬至】湖中的天鹅，中国新疆伊犁州 (© SinoImages/Getty Images)","copyrightlink":"http://www.bing.com/search?q=%E5%86%AC%E8%87%B3&form=hpcapt&mkt=zh-cn","quiz":"/search?q=Bing+homepage+quiz&filters=WQOskey:%22HPQuiz_20171221_Wintersolstice1222%22&FORM=HPQUIZ","wp":true,"hsh":"db6633f100b9b5f91651376c73d0e222","drk":1,"top":1,"bot":1,"hs":[]}],"tooltips":{"loading":"正在加载...","previous":"上一个图像","next":"下一个图像","walle":"此图片不能下载用作壁纸。","walls":"下载今日美图。仅限用作桌面壁纸。"}}`

**Comment by yichangshengwu** [comment]
要是，一个地方可以找齐国内版和国际版的壁纸就好啦
