### ISSUE TITLE
为什么获取的图片会有bing水印呢，对于强迫症患者好纠结呀

### ISSUE THREAD

**Issue by xperezxin** [xCss/bing#30]
使用的是这个参数：[http://bing.ioliu.cn/v1?w=1920&h=1200](http://bing.ioliu.cn/v1?w=1920&h=1200)
![每日壁纸](http://bing.ioliu.cn/v1?w=1920&h=1200 "图片上面有个Bing水印")

**Comment by xCss** [comment]
@xperezxin 这个水印是bing官方加的，我这边拿到的就是有水印的图的，只是针对1920x1200分辨率。

其他分辨率不会有水印。

祝好。

**Comment by Chen-Hu** [comment]
用这个链接
http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
从bing.com
解析出来的是不带水印的图。

**Comment by xCss** [comment]
@Chen-Hu 谁说不带的？
https://cn.bing.com/az/hprichbg/rb/RosehipRobin_EN-US10765383343_1920x1200.jpg
![tim 20171222165717](https://user-images.githubusercontent.com/10877162/34291844-3236d490-e739-11e7-9c98-21e13394ecae.jpg)

**Comment by Chen-Hu** [comment]
不好意思没看清楚分辨了

**Comment by xperezxin** [comment]
确实是这样，我直接抓取官方的图片也是有水印的，这就没办法了！:blush:
