### ISSUE TITLE
How to use it with curl?

### ISSUE THREAD

**Issue by wsdjeg** [xCss/bing#31]
I want to use it in cli, so, how can I get info from the api via curl?

```
curl http://bing.ioliu.cn/v1?w=1920&h=1200
```

show status: 301

**Comment by xCss** [comment]
@wsdjeg `301` means redirect.
you can try using `https`:
```bash
curl https://bing.ioliu.cn/v1?w=1920&h=1200
```

**Comment by wsdjeg** [comment]
Thank you！
