### ISSUE TITLE
打开流失败。

### ISSUE THREAD

**Issue by jamieego** [xCss/bing#36]
Warning: require_once(config.php): failed to open stream: No such file or directory in D:\phpStudy\WWW\bing\lib\base.php on line 11

Fatal error: require_once(): Failed opening required 'config.php' (include_path='.;C:\php\pear') in D:\phpStudy\WWW\bing\lib\base.php on line 11

请问怎么解决
谢谢

**Comment by xCss** [comment]
你的`config.php`文件在`base.php`文件同级吗？
