### ISSUE TITLE
你好，我想问下你的这些数据是从必应首页每天获取的么？还是其他什么方式？

### ISSUE THREAD

**Issue by wycm** [xCss/bing#4]

**Comment by xCss** [comment]
是的，每天从bing首页获取的

**Comment by 523860169** [comment]
@xCss 好像挂了，返回{"data":{"IP":"112.5.237.38","Info":"Please Set URL Like This: http://bing.ioliu.cn/v1/?url=http[s]://YourWantProxyUrl.Com"},"status":{"code":200,"message":""}}

**Comment by xCss** [comment]
@523860169  能把你的具体调用方式与调用接口写出来吗？

如果可以的话，麻烦把参数也写出来。

对了，这里是bing壁纸的接口。。。

**Comment by 523860169** [comment]
@xCss 直接浏览器打开http://bing.ioliu.cn/v1?w=1366&h=768，就变成那样了

**Comment by xCss** [comment]
@523860169 表示我这边没有这个问题，http://bing.ioliu.cn/v1?w=1366&h=768 这个显示的直接是一张图片，如下图:
![](http://bing.ioliu.cn/v1?w=1366&h=768)
