### ISSUE TITLE
倒数第975张的缩略图和实图不一致

### ISSUE THREAD

**Issue by GoGoogle** [xCss/bing#40]
https://bing.ioliu.cn/?p=11

http://h1.ioliu.cn/bing/AutumnNeuschwanstein_EN-AU10604288553_800x480.jpg

原因是什么呢？

**Comment by GoGoogle** [comment]
#update
第11页倒数第1张。（由于每天采集，所以还在变化）

**Comment by xCss** [comment]
已修复~

**Comment by GoGoogle** [comment]
其实我想要这张图，终于找到了。
https://www.bing.com/sa/simg/hpb/NorthMale_EN-US8782628354_1920x1080.jpg
