### ISSUE TITLE
请问作者，原图真实分辨率最大是多少呀？

### ISSUE THREAD

**Issue by wangzhijun97** [xCss/bing#50]
请问作者，原图真实分辨率最大是多少呀？

**Comment by xCss** [comment]
1920x1080就是原图真实分辨率~

**Comment by wangzhijun97** [comment]
> 1920x1080就是原图真实分辨率~

Bing的每日图片最大就是1920*1080吗？

**Comment by xCss** [comment]
@wangzhijun97 某些图有1920x1200，但是含有bing的logo

**Comment by wangzhijun97** [comment]
> @wangzhijun97 某些图有1920x1200，但是含有bing的logo

👍
