### ISSUE TITLE
-label:bug 挂掉了么？

### ISSUE THREAD

**Issue by HelloW0r1d** [xCss/bing#7]
-label:bug 
你好，亲爱的作者。今天我在使用您的api的时候`background-image:url(//bing.ioliu.cn/v1?w=1920&h=1080)`返回了如下值`{"data":{"IP":"118.149.110.213","Info":"Please Set URL Like This: http://bing.ioliu.cn/v1/?url=http[s]://YourWantProxyUrl.Com"},"status":{"code":200,"message":""}}`是使用方法改变了还是以后不再提供服务了？

**Comment by xCss** [comment]
@HelloW0r1d 很抱歉，由于我的操作失误，让壁纸服务挂掉了，现已恢复正常，请重试 ^_^

**Comment by HelloW0r1d** [comment]
谢谢！！我爱你！！我不是gay！

**Comment by HelloW0r1d** [comment]
技术上的爱orz

**Comment by xCss** [comment]
- -~!
