### ISSUE TITLE
Transfer Domain

### ISSUE THREAD

**Issue by ngchwanlii-bestsell** [xCss/bing#74]
Hi 您好 @xCss,

我也是程序猿一枚 （后端的），人在马来西亚， 现在正在创业中，看中了这个 bestselll.com 的域名，不知道您是否能够出让这个域名？ 这个域名符合我们当地的标题习惯所以我真的诚心的希望您能够出让，如果价格合理可以跟你买下， 实话说，我现在创业中资金确实有限，程序也是一行一行的敲，这里没什么人学计算机的，继续折腾着，哈哈。

期待您的回复!

**Comment by xCss** [comment]
你好，不知道你在哪查到这个域名属于我，但实际上我并没有注册过`bestselll.com` 这个域名。

抱歉，帮不了你，祝好！

**Comment by ngchwanlii-bestsell** [comment]
@xCss 您好，谢谢回复，我看了这篇文章，跟着  [Github 链接](http://bestsell.com/static/about.html), 找到这里的，你确定不是您的吗？

**Comment by xCss** [comment]
早上好，
这个网站内容虽然是我的，但是这个域名是却不是我的，应该是某位[必应壁纸](https://bing.ioliu.cn)爱好者修改了源码然后解析到了这个域名，你需要联系这个域名留下的邮箱。不过看起来是信息保密的。

[![image](https://user-images.githubusercontent.com/10877162/178385931-bb34457f-7b6d-41bb-8817-37177a1532c4.png)](https://user-images.githubusercontent.com/10877162/178385931-bb34457f-7b6d-41bb-8817-37177a1532c4.png)

**Comment by ngchwanlii-bestsell** [comment]
好的，谢谢！
