### ISSUE TITLE
请教博主一个mysqli_fetch_assoc()的问题

### ISSUE THREAD

**Issue by Ryongyon** [xCss/bing#8]
我下载的是PHP的源码，填好相关信息后访问主页提示一下错误，请问博主是什么原因导致的？（只填写了必要填的信息配置，数据库信息以及七牛，其他代码没改动）

Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in D:\phpStudy\WWW\lib\base.php on line 395

Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in D:\phpStudy\WWW\lib\base.php on line 176

**Comment by xCss** [comment]
@Ryongyon 很抱歉，从错误信息来看，并不能找到错误的根源。但可以从以下三个方面着手解决问题：
- 1. 查看数据库链接配置，确保连接没问题
- 2. 检查数据表结构
- 3. 确认sql语句与数据表字段对应
